### ISSUE TITLE
Exception: bitget amount of ETH/USDT:USDT must be greater than minimum amount precision of 0.01

### ISSUE THREAD

**Issue by ekoume** [CryptoRobotFr/live_tools#14]
Bonjour,
J obtiens l erreur: 

Balance: 60.0 $
Place sell order (envelope 1) of 0.009228038727933945 ETH/USDT:USDT at price 2167.31 $
Traceback (most recent call last):
  File "/home/ubuntu/trading_folder/strategy_enveloppe/./live_tools/utilities/perp_bitget.py", line 94, in place_limit_order
    self.convert_amount_to_precision(symbol, amount), 
  File "/home/ubuntu/trading_folder/strategy_enveloppe/./live_tools/utilities/perp_bitget.py", line 82, in convert_amount_to_precision
    return self._session.amount_to_precision(symbol, amount)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ccxt/base/exchange.py", line 3304, in amount_to_precision
    raise ArgumentsRequired(self.id + ' amount of ' + market['symbol'] + ' must be greater than minimum amount precision of ' + self.number_to_string(market['precision']['amount']))
ccxt.base.errors.ArgumentsRequired: bitget amount of ETH/USDT:USDT must be greater than minimum amount precision of 0.01

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/trading_folder/strategy_enveloppe/live_tools/strategies/envelope/strategy_bitget.py", line 121, in <module>
    bitget.place_limit_order(
  File "/home/ubuntu/trading_folder/strategy_enveloppe/./live_tools/utilities/perp_bitget.py", line 32, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/ubuntu/trading_folder/strategy_enveloppe/./live_tools/utilities/perp_bitget.py", line 99, in place_limit_order
    raise Exception(err)
Exception: bitget amount of ETH/USDT:USDT must be greater than minimum amount precision of 0.01

Quelle peut etre la solution a votre avis?

**Comment by liroycousin** [comment]
j'ai le même problème et je n'ai pas trouver la solution la tu trouver depuis ?
