### ISSUE TITLE
Marge isolée en stratégie enveloppe

### ISSUE THREAD

**Issue by grosjeje3123** [CryptoRobotFr/live_tools#19]
Bonjour,
Merci pour cette belle stratégie d'enveloppe.
Mais j'ai remarqué que de base, on est en marge croisée. J'ai tenté de passer en marge isolée, en ajoutant "params={'marginMode':'fixed','leverage': 1}," aux "bitget.place_limit_order" mais ça renvoie une erreur. C'est le perp.bitget.py qui semble poser problème : 

Place sell order (envelope 1) of 0.002 BTC/USDT:USDT at price 49406.43 $
Traceback (most recent call last):
  File "/home/ubuntu/live_tools/strategies/envelope/bitget_multi_token_enveloppe.py", line 257, in <module>
    bitget.place_limit_order(
  File "/home/ubuntu/./live_tools/utilities/perp_bitget.py", line 32, in wrapped
    return fn(self, *args, **kwargs)
TypeError: PerpBitget.place_limit_order() got an unexpected keyword argument 'params'

Merci par avance pour l'aide

jerome

**Comment by grosjeje3123** [comment]
Il faut juste que je rajoute ce paramètre dans la fonction "place_limit_order" dans perp.bitget.py?
