### ISSUE TITLE
limitation timeframe

### ISSUE THREAD

**Issue by seblezinzin** [CryptoRobotFr/live_tools#2]
Bonjour,

Je souhaitais basculer la timeframe en 1min au lieu de 1H mais j'obtiens ce message : 
/live_tools/utilities/perp_bitget.py:62: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  full_result = np.array(full_result).reshape(-1,6)
Traceback (most recent call last):
  File "/live_tools/strategies/bol_trend/strategy_bitget2.py", line 75, in <module>
    df = bitget.get_more_last_historical_async(pair, timeframe, 1000)
  File "/live_tools/utilities/perp_bitget.py", line 62, in get_more_last_historical_async
    full_result = np.array(full_result).reshape(-1,6)

une idée?

**Comment by Amyaas1** [comment]
A la place de 1000 mis 100 ou 90
df = bitget.get_more_last_historical_async(pair, timeframe, 100)

**Comment by pikafou** [comment]
Bonjour,
J'ai eu le même problème, as-tu mis timeframe = "1m" pour changer en 1mn?
J'ai aucun trade qui se lance
