### ISSUE TITLE
Problème à l'execution 

### ISSUE THREAD

**Issue by Zilk66** [CryptoRobotFr/live_tools#8]
Bonjour,
Lors de l'execution, je me suis retrouvé avec ces lignes je pense que ce sont des erreurs, mais je ne comprends rien.
Merci aux bonnes âmes qui pourront m'aider.
--- Start Execution Time : 02/04/2023 15:59:23 ---
Traceback (most recent call last):
  File "/home/ubuntu/live_tools/strategies/bol_trend/strategy_multi_bitget.py", line 21, in <module>
    secret = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 18 (char 18)

**Comment by CryptoRobotFr** [comment]
Bonjour cette erreur est du a une erreur de format dans le fichier secret.json (au charactère 18 de la ligne 2. Le plus souvent c'est qu'il manque une virgule à la fin de la ligne ou quelque chose comme ça

**Comment by Zilk66** [comment]
Merci beaucoup, il manquait juste un { au début du fichier.
